CREATE DATABASE IF NOT EXISTS `Baitaplon` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `Baitaplon`;

CREATE TABLE IF NOT EXISTS `taikhoan` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `hoten` VARCHAR(100) NOT NULL,
  `role` INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `Danhmuc` (
  `MaDM` INT AUTO_INCREMENT PRIMARY KEY,
  `MaCode` VARCHAR(50) NOT NULL,
  `TenDM` VARCHAR(255) NOT NULL,
  `MoTa` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `nhacungcap` (
  `MaNCC` INT AUTO_INCREMENT PRIMARY KEY,
  `MaCode` VARCHAR(50) NOT NULL,
  `TenNCC` VARCHAR(255) NOT NULL,
  `DienThoai` VARCHAR(20) NOT NULL,
  `DiaChi` VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `Nhanvien` (
  `MaNV` VARCHAR(50) PRIMARY KEY,
  `HoTen` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(100),
  `ChucVu` VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `Khachhang` (
  `MaKH` VARCHAR(50) PRIMARY KEY,
  `TenKH` VARCHAR(100) NOT NULL,
  `DienThoai` VARCHAR(20) NOT NULL,
  `DiemTichLuy` INT NOT NULL DEFAULT 0,
  `DiaChi` VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `phuongthucthanhtoan` (
  `MaPT` INT AUTO_INCREMENT PRIMARY KEY,
  `TenPT` VARCHAR(100) NOT NULL,
  `TrangThai` INT NOT NULL DEFAULT 1,
  `HinhAnh` VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `Khuyenmai` (
  `MaKM` INT AUTO_INCREMENT PRIMARY KEY,
  `TenMa` VARCHAR(50) NOT NULL,
  `SoTienGiam` INT NOT NULL DEFAULT 0,
  `SoLuong` INT NOT NULL DEFAULT 0,
  `TrangThai` INT NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `Sanpham` (
  `MaSP` VARCHAR(50) PRIMARY KEY,
  `TenSP` VARCHAR(255) NOT NULL,
  `MaDM` INT NOT NULL,
  `MaNCC` INT NOT NULL,
  `GiaBan` INT NOT NULL DEFAULT 0,
  `SoLuongTon` INT NOT NULL DEFAULT 0,
  `HinhAnh` VARCHAR(255),
  `HanSuDung` DATE DEFAULT NULL,
  FOREIGN KEY (`MaDM`) REFERENCES `Danhmuc`(`MaDM`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`MaNCC`) REFERENCES `nhacungcap`(`MaNCC`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `Donhang` (
  `MaHD` INT AUTO_INCREMENT PRIMARY KEY,
  `MaKH` VARCHAR(50) NOT NULL,
  `MaNV` VARCHAR(50) NOT NULL,
  `NgayLap` DATETIME NOT NULL,
  `TongTien` INT NOT NULL DEFAULT 0,
  `GiamGia` INT NOT NULL DEFAULT 0,
  `MaPT` INT NOT NULL,
  `TrangThai` INT NOT NULL DEFAULT 1,
  FOREIGN KEY (`MaKH`) REFERENCES `Khachhang`(`MaKH`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`MaNV`) REFERENCES `Nhanvien`(`MaNV`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`MaPT`) REFERENCES `phuongthucthanhtoan`(`MaPT`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ChitietDonhang` (
  `MaHD` INT NOT NULL,
  `MaSP` VARCHAR(50) NOT NULL,
  `SoLuong` INT NOT NULL DEFAULT 0,
  `DonGia` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`MaHD`, `MaSP`),
  FOREIGN KEY (`MaHD`) REFERENCES `Donhang`(`MaHD`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`MaSP`) REFERENCES `Sanpham`(`MaSP`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `Phieunhap` (
  `MaPN` INT AUTO_INCREMENT PRIMARY KEY,
  `MaNCC` INT NOT NULL,
  `MaNV` VARCHAR(50) NOT NULL,
  `NgayNhap` DATETIME NOT NULL,
  `TongTien` INT NOT NULL DEFAULT 0,
  FOREIGN KEY (`MaNCC`) REFERENCES `nhacungcap`(`MaNCC`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`MaNV`) REFERENCES `Nhanvien`(`MaNV`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ChitietPhieunhap` (
  `MaPN` INT NOT NULL,
  `MaSP` VARCHAR(50) NOT NULL,
  `SoLuong` INT NOT NULL DEFAULT 0,
  `DonGia` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`MaPN`, `MaSP`),
  FOREIGN KEY (`MaPN`) REFERENCES `Phieunhap`(`MaPN`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`MaSP`) REFERENCES `Sanpham`(`MaSP`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `phieukiem` (
  `MaPK` INT AUTO_INCREMENT PRIMARY KEY,
  `MaNV` VARCHAR(50) NOT NULL,
  `NgayKiem` DATETIME NOT NULL,
  `GhiChu` TEXT,
  FOREIGN KEY (`MaNV`) REFERENCES `Nhanvien`(`MaNV`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `chitietkiem` (
  `MaPK` INT NOT NULL,
  `MaSP` VARCHAR(50) NOT NULL,
  `TonMay` INT NOT NULL DEFAULT 0,
  `TonThuc` INT NOT NULL DEFAULT 0,
  `LyDo` TEXT,
  PRIMARY KEY (`MaPK`, `MaSP`),
  FOREIGN KEY (`MaPK`) REFERENCES `phieukiem`(`MaPK`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`MaSP`) REFERENCES `Sanpham`(`MaSP`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
